apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  annotations:
    federation.alpha.kubernetes.io/cluster-selector: 
      '[{
        "key": "privacy",
        "operator": "In",
        "values": ["public"]
      }]'
  namespace: demo
spec:
  replicas: 4
  template:
    metadata:
      labels:
        run: hello-world-deployment
    spec:
      containers:
      - name: hello-world-container
        image: vinhags/hw-flask:2.2
        ports:
        - containerPort: 8080
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CLUSTER_NAME
            valueFrom:
              configMapKeyRef:
                name: cluster-config
                key: cluster.name