apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  annotations:
    federation.alpha.kubernetes.io/cluster-selector: 
      '[{
        "key": "privacy",
        "operator": "In",
        "values": ["private"]
      }]'
  namespace: demo
spec:
  replicas: 4
  template:
    metadata:
      labels:
        run: hello-world-deployment
    spec:
      containers:
      - name: hello-world-container
        image: vinhags/hw-flask:2.1
        ports:
        - containerPort: 8080
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
